name: Test
on:
  # Manual trigger
  workflow_dispatch:  
  push:
    branches: main
  pull_request:
  
permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.23', '1.24' ]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Check out code
      uses: actions/checkout@v4
    - name: Test
      run: go test -v ./...
